set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(PREFIX "${CMAKE_CURRENT_LIST_DIR}/prefix")
set(TRIPLE "x86_64-elf")

set(CMAKE_C_COMPILER_TARGET "${TRIPLE}")
set(CMAKE_CXX_COMPILER_TARGET "${TRIPLE}")

set(CMAKE_C_COMPILER "${PREFIX}/bin/${TRIPLE}-gcc${CMAKE_HOST_EXECUTABLE_SUFFIX}")
set(CMAKE_CXX_COMPILER "${PREFIX}/bin/${TRIPLE}-g++${CMAKE_HOST_EXECUTABLE_SUFFIX}")
set(CMAKE_ASM_COMPILER "${PREFIX}/bin/${TRIPLE}-gcc${CMAKE_HOST_EXECUTABLE_SUFFIX}")
set(CMAKE_AR "${PREFIX}/bin/${TRIPLE}-ar${CMAKE_HOST_EXECUTABLE_SUFFIX}")
set(CMAKE_RANLIB "${PREFIX}/bin/${TRIPLE}-ranlib${CMAKE_HOST_EXECUTABLE_SUFFIX}")
set(CMAKE_LINKER "${PREFIX}/bin/${TRIPLE}-ld${CMAKE_HOST_EXECUTABLE_SUFFIX}")
set(CMAKE_OBJCOPY "${PREFIX}/bin/${TRIPLE}-objcopy${CMAKE_HOST_EXECUTABLE_SUFFIX}")
set(CMAKE_OBJDUMP "${PREFIX}/bin/${TRIPLE}-objdump${CMAKE_HOST_EXECUTABLE_SUFFIX}")
set(CMAKE_STRIP "${PREFIX}/bin/${TRIPLE}-strip${CMAKE_HOST_EXECUTABLE_SUFFIX}")

set(CMAKE_C_FLAGS_INIT "${CMAKE_C_FLAGS_INIT} -nostdlib")
set(CMAKE_CXX_FLAGS_INIT "${CMAKE_CXX_FLAGS_INIT} -nostdlib")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
